# Generated by Django 2.2.20 on 2021-04-21 10:52

from django.db import migrations, models
import djongo.models.fields
import quizdb.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=20)),
                ('questions', djongo.models.fields.ArrayField(model_container=quizdb.models.Question, model_form_class=quizdb.models.QuestionForm)),
            ],
        ),
    ]
